# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tolokaforge/agent/agent.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "tolokaforge/agent/agent.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1dtolokaforge/agent/agent.proto\x12\x05\x61gent"\xe0\x01\n\x0c\x41gentRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x10\n\x08trial_id\x18\x02 \x01(\t\x12,\n\x14\x63onversation_history\x18\x03 \x03(\x0b\x32\x0e.agent.Message\x12*\n\x0f\x61vailable_tools\x18\x04 \x03(\x0b\x32\x11.agent.ToolSchema\x12(\n\x0cmodel_config\x18\x05 \x01(\x0b\x32\x12.agent.ModelConfig\x12\x15\n\rsystem_prompt\x18\x06 \x01(\t\x12\x12\n\nmax_tokens\x18\x07 \x01(\x05"\x95\x01\n\rAgentResponse\x12$\n\ttool_call\x18\x01 \x01(\x0b\x32\x0f.agent.ToolCallH\x00\x12.\n\x0e\x66inal_response\x18\x02 \x01(\x0b\x32\x14.agent.FinalResponseH\x00\x12$\n\x07metrics\x18\x03 \x01(\x0b\x32\x13.agent.AgentMetricsB\x08\n\x06\x61\x63tion"M\n\x07Message\x12\x0c\n\x04role\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12#\n\ntool_calls\x18\x03 \x03(\x0b\x32\x0f.agent.ToolCall"<\n\x08ToolCall\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x16\n\x0e\x61rguments_json\x18\x03 \x01(\t" \n\rFinalResponse\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t"H\n\nToolSchema\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x17\n\x0fparameters_json\x18\x03 \x01(\t"d\n\x0bModelConfig\x12\x10\n\x08provider\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0btemperature\x18\x03 \x01(\x01\x12\x0c\n\x04seed\x18\x04 \x01(\x05\x12\x12\n\nmax_tokens\x18\x05 \x01(\x05"\x81\x01\n\x0c\x41gentMetrics\x12\x15\n\rprompt_tokens\x18\x01 \x01(\x05\x12\x19\n\x11\x63ompletion_tokens\x18\x02 \x01(\x05\x12\x14\n\x0ctotal_tokens\x18\x03 \x01(\x05\x12\x10\n\x08\x63ost_usd\x18\x04 \x01(\x01\x12\x17\n\x0flatency_seconds\x18\x05 \x01(\x01"\x14\n\x12HealthCheckRequest"6\n\x13HealthCheckResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t2\x90\x01\n\x0c\x41gentService\x12:\n\rGetNextAction\x12\x13.agent.AgentRequest\x1a\x14.agent.AgentResponse\x12\x44\n\x0bHealthCheck\x12\x19.agent.HealthCheckRequest\x1a\x1a.agent.HealthCheckResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "tolokaforge.agent.agent_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_AGENTREQUEST"]._serialized_start = 41
    _globals["_AGENTREQUEST"]._serialized_end = 265
    _globals["_AGENTRESPONSE"]._serialized_start = 268
    _globals["_AGENTRESPONSE"]._serialized_end = 417
    _globals["_MESSAGE"]._serialized_start = 419
    _globals["_MESSAGE"]._serialized_end = 496
    _globals["_TOOLCALL"]._serialized_start = 498
    _globals["_TOOLCALL"]._serialized_end = 558
    _globals["_FINALRESPONSE"]._serialized_start = 560
    _globals["_FINALRESPONSE"]._serialized_end = 592
    _globals["_TOOLSCHEMA"]._serialized_start = 594
    _globals["_TOOLSCHEMA"]._serialized_end = 666
    _globals["_MODELCONFIG"]._serialized_start = 668
    _globals["_MODELCONFIG"]._serialized_end = 768
    _globals["_AGENTMETRICS"]._serialized_start = 771
    _globals["_AGENTMETRICS"]._serialized_end = 900
    _globals["_HEALTHCHECKREQUEST"]._serialized_start = 902
    _globals["_HEALTHCHECKREQUEST"]._serialized_end = 922
    _globals["_HEALTHCHECKRESPONSE"]._serialized_start = 924
    _globals["_HEALTHCHECKRESPONSE"]._serialized_end = 978
    _globals["_AGENTSERVICE"]._serialized_start = 981
    _globals["_AGENTSERVICE"]._serialized_end = 1125
# @@protoc_insertion_point(module_scope)
