# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from tolokaforge.agent import agent_pb2 as tolokaforge_dot_agent_dot_agent__pb2

GRPC_GENERATED_VERSION = "1.75.1"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in tolokaforge/agent/agent_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class AgentServiceStub:
    """Agent service - runs LLM to generate next action"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetNextAction = channel.unary_unary(
            "/agent.AgentService/GetNextAction",
            request_serializer=tolokaforge_dot_agent_dot_agent__pb2.AgentRequest.SerializeToString,
            response_deserializer=tolokaforge_dot_agent_dot_agent__pb2.AgentResponse.FromString,
            _registered_method=True,
        )
        self.HealthCheck = channel.unary_unary(
            "/agent.AgentService/HealthCheck",
            request_serializer=tolokaforge_dot_agent_dot_agent__pb2.HealthCheckRequest.SerializeToString,
            response_deserializer=tolokaforge_dot_agent_dot_agent__pb2.HealthCheckResponse.FromString,
            _registered_method=True,
        )


class AgentServiceServicer:
    """Agent service - runs LLM to generate next action"""

    def GetNextAction(self, request, context):
        """Get next action from agent given conversation history"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def HealthCheck(self, request, context):
        """Health check"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_AgentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GetNextAction": grpc.unary_unary_rpc_method_handler(
            servicer.GetNextAction,
            request_deserializer=tolokaforge_dot_agent_dot_agent__pb2.AgentRequest.FromString,
            response_serializer=tolokaforge_dot_agent_dot_agent__pb2.AgentResponse.SerializeToString,
        ),
        "HealthCheck": grpc.unary_unary_rpc_method_handler(
            servicer.HealthCheck,
            request_deserializer=tolokaforge_dot_agent_dot_agent__pb2.HealthCheckRequest.FromString,
            response_serializer=tolokaforge_dot_agent_dot_agent__pb2.HealthCheckResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "agent.AgentService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("agent.AgentService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class AgentService:
    """Agent service - runs LLM to generate next action"""

    @staticmethod
    def GetNextAction(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/agent.AgentService/GetNextAction",
            tolokaforge_dot_agent_dot_agent__pb2.AgentRequest.SerializeToString,
            tolokaforge_dot_agent_dot_agent__pb2.AgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def HealthCheck(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/agent.AgentService/HealthCheck",
            tolokaforge_dot_agent_dot_agent__pb2.HealthCheckRequest.SerializeToString,
            tolokaforge_dot_agent_dot_agent__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
