# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from tolokaforge.grader import grader_pb2 as grader__pb2

GRPC_GENERATED_VERSION = "1.83.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in grader_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class GraderServiceStub:
    """=============================================================================
    Grader Service — dedicated Grade RPC, independent of the runner surface.
    =============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Grade = channel.unary_unary(
            "/tolokaforge.grader.GraderService/Grade",
            request_serializer=grader__pb2.GradeRequest.SerializeToString,
            response_deserializer=grader__pb2.GradeResponse.FromString,
            _registered_method=True,
        )
        self.HealthCheck = channel.unary_unary(
            "/tolokaforge.grader.GraderService/HealthCheck",
            request_serializer=grader__pb2.HealthCheckRequest.SerializeToString,
            response_deserializer=grader__pb2.HealthCheckResponse.FromString,
            _registered_method=True,
        )


class GraderServiceServicer:
    """=============================================================================
    Grader Service — dedicated Grade RPC, independent of the runner surface.
    =============================================================================

    """

    def Grade(self, request, context):
        """Compute a Grade for a completed trial.

        Stateless per call: the caller provides everything the grader needs to
        produce a verdict (the transcript encoded as LLM messages, the trial's
        termination reason, and — for a future extension carrying rubric config
        — the task_config JSON). The grader is expected to be reachable at a
        different address from the runner service; the wire types are decoupled
        from runner.proto so the two services can rev on their own cadence.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def HealthCheck(self, request, context):
        """Health check — same shape as runner.HealthCheck for operational parity."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_GraderServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Grade": grpc.unary_unary_rpc_method_handler(
            servicer.Grade,
            request_deserializer=grader__pb2.GradeRequest.FromString,
            response_serializer=grader__pb2.GradeResponse.SerializeToString,
        ),
        "HealthCheck": grpc.unary_unary_rpc_method_handler(
            servicer.HealthCheck,
            request_deserializer=grader__pb2.HealthCheckRequest.FromString,
            response_serializer=grader__pb2.HealthCheckResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "tolokaforge.grader.GraderService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("tolokaforge.grader.GraderService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class GraderService:
    """=============================================================================
    Grader Service — dedicated Grade RPC, independent of the runner surface.
    =============================================================================

    """

    @staticmethod
    def Grade(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/tolokaforge.grader.GraderService/Grade",
            grader__pb2.GradeRequest.SerializeToString,
            grader__pb2.GradeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def HealthCheck(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/tolokaforge.grader.GraderService/HealthCheck",
            grader__pb2.HealthCheckRequest.SerializeToString,
            grader__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
