"""Queue-backed grader transport — the throughput seam (ADR-0038, P3).

Where :class:`GraderRPCTrialGrader` gives the orchestrator *independent
deploy* (a grader on a different machine), the queue-backed transport gives
it *independent throughput scale*: the orchestrator publishes a grade job
and its worker thread returns immediately, freeing it to run the next
trial. A pool of grader workers consumes from the queue in parallel; the
scale knob is the consumer count. Native back-pressure is inherited from
the queue.

Two moving parts:

- :class:`GradeBroker` — Protocol for the transport. Producers call
  :meth:`publish_job` and get a :class:`concurrent.futures.Future` back;
  consumers call :meth:`next_job` (blocking) and :meth:`publish_result`.
- :class:`InMemoryGradeBroker` — a reference impl using
  :class:`queue.Queue` + a per-trial ``Future`` map. Ships as the
  in-process transport for tests, single-machine deployments, and the
  keyless integration-test tier. A Redis Streams (or RabbitMQ / SQS)
  backend plugs behind the same Protocol — deferred to a follow-up
  because the wire contract, the reference impl, and the plug-in seam
  can prove the throughput property today.

The plug-in seam consumer is
:class:`~tolokaforge.core.trial_grader.QueueTrialGrader`, registered
under the ``queue`` entry point.
"""

from __future__ import annotations

import queue
import threading
import uuid
from concurrent.futures import Future
from dataclasses import dataclass, field
from typing import Protocol, runtime_checkable

from tolokaforge.core.models import Grade

_CLOSE_SENTINEL: object = object()
"""Marker put on the queue by :meth:`InMemoryGradeBroker.close` so consumers
parked in :meth:`~InMemoryGradeBroker.next_job` (default ``timeout=None``)
unblock and terminate cleanly on shutdown."""


class BrokerClosed(Exception):
    """Raised by :meth:`GradeBroker.next_job` when the broker has been closed.

    Distinguishes "broker shut down, stop consuming" from "queue is empty
    right now, try again" — a returned ``None`` reads only as the latter, so
    consumers can retry safely without checking a private ``_closed`` flag.
    """


@dataclass(frozen=True)
class GradeJob:
    """A grade-request the producer puts on the queue.

    ``job_id`` is the join key between the producer (which blocks on a
    :class:`Future` keyed by it) and the consumer (which returns a
    :class:`GradeResult` carrying the same id). Producers should not
    read into ``job_id``'s value — it is opaque and generated by the
    broker.

    Fields mirror :class:`grader_pb2.GradeRequest` — each is a wire field the
    :class:`~tolokaforge.grader.queue._queue_worker_loop` forwards verbatim
    to :meth:`GrpcGraderClient.grade`. Every downstream substrate address,
    task description, and judge model config the composite dispatcher needs
    to grade the trial rides on the job.
    """

    job_id: str
    trial_id: str
    llm_messages_json: str
    termination_reason: str
    task_config_json: str
    judge_model_config_json: str
    task_description_json: str
    runner_substrate_address: str
    agent_system_prompt: str


@dataclass(frozen=True)
class GradeResult:
    """A grade-response the consumer publishes back onto the broker."""

    job_id: str
    grade: Grade | None
    error: str = ""


@runtime_checkable
class GradeBroker(Protocol):
    """Transport surface the queue-backed grader dispatches through.

    Implementations may back onto any queue substrate (Redis Streams,
    RabbitMQ, SQS, an in-process :class:`queue.Queue`); the plug-in seam
    stays behind this Protocol.
    """

    def publish_job(self, job: GradeJob) -> Future[Grade | None]: ...

    def next_job(self, timeout: float | None = None) -> GradeJob | None: ...

    def publish_result(self, result: GradeResult) -> None: ...

    def cancel_job(self, job_id: str) -> None: ...

    def close(self) -> None: ...


@dataclass
class InMemoryGradeBroker:
    """Reference :class:`GradeBroker` backed by a :class:`queue.Queue`.

    Thread-safe: producers on any thread can call :meth:`publish_job`,
    consumers on any thread can call :meth:`next_job` and
    :meth:`publish_result`. Ships as the in-process transport for tests
    and single-machine deployments; a Redis Streams (or other) backend
    plugs behind :class:`GradeBroker` without touching the seam
    consumer.

    The broker owns the per-job :class:`Future` — the producer receives
    it, the consumer's :meth:`publish_result` resolves it.

    Return-value contract for :meth:`next_job`:

    - a :class:`GradeJob` when one is available before the timeout,
    - ``None`` when the timeout elapses on an empty queue (retry),
    - :class:`BrokerClosed` when :meth:`close` has been called (stop).

    ``publish_result`` after :meth:`close` is a no-op — the future the
    caller was waiting on has already been failed with ``broker closed``,
    so a worker publishing a result it computed in flight has nothing
    to hand back but should not crash.
    """

    _q: queue.Queue[GradeJob] = field(default_factory=queue.Queue)
    _futures: dict[str, Future[Grade | None]] = field(default_factory=dict)
    _futures_lock: threading.Lock = field(default_factory=threading.Lock)
    _closed: bool = False

    def publish_job(self, job: GradeJob) -> Future[Grade | None]:
        future: Future[Grade | None] = Future()
        # ``_closed`` and ``_futures`` share one critical section so a
        # concurrent :meth:`close` cannot slip in between the check and
        # the insert and orphan the returned future. Every future the
        # caller ever receives is either resolved by :meth:`publish_result`
        # or failed by :meth:`close`.
        with self._futures_lock:
            if self._closed:
                raise RuntimeError("InMemoryGradeBroker is closed")
            self._futures[job.job_id] = future
        self._q.put(job)
        return future

    def next_job(self, timeout: float | None = None) -> GradeJob | None:
        try:
            job = self._q.get(timeout=timeout)
        except queue.Empty:
            return None
        # ``close()`` puts a sentinel on the queue so a consumer parked in
        # ``next_job(timeout=None)`` (the default) unblocks and terminates
        # cleanly instead of hanging on shutdown. Re-post the sentinel so
        # multiple consumers each see it, and raise :class:`BrokerClosed`
        # so the caller can distinguish "closed" from the timeout branch's
        # ``None``.
        if job is _CLOSE_SENTINEL:
            self._q.put(_CLOSE_SENTINEL)
            raise BrokerClosed("broker is closed")
        return job

    def publish_result(self, result: GradeResult) -> None:
        with self._futures_lock:
            future = self._futures.pop(result.job_id, None)
        # Two legitimate misses: the broker was closed and cleared this
        # future before the worker returned (the caller already sees
        # ``broker closed``, no re-notification needed), or the job id
        # never came from this broker's :meth:`publish_job`. The first is
        # not a bug; the second is a wire-level defect that a caller
        # would want to see. The KeyError message keeps the second
        # visible without turning the first into a crash.
        if future is None:
            if self._closed:
                return
            raise KeyError(
                f"publish_result: no outstanding job {result.job_id!r} — "
                "duplicate id or job never published"
            )
        if result.error:
            future.set_exception(RuntimeError(result.error))
        else:
            future.set_result(result.grade)

    def cancel_job(self, job_id: str) -> None:
        """Remove ``job_id``'s future entry — used by callers that gave up
        on a slow worker (timeout, cancellation). Idempotent; safe to call
        after :meth:`publish_result` has already resolved the entry."""
        with self._futures_lock:
            self._futures.pop(job_id, None)

    def close(self) -> None:
        # Unblock any consumer parked in ``next_job(timeout=None)``. The
        # sentinel re-posts itself so a pool of N consumers each terminates
        # rather than one racing ahead and starving the rest.
        with self._futures_lock:
            self._closed = True
            futures = list(self._futures.values())
            self._futures.clear()
        self._q.put(_CLOSE_SENTINEL)
        for future in futures:
            if not future.done():
                future.set_exception(RuntimeError("broker closed"))


def new_job_id() -> str:
    """Broker-side job-id generator. Callers should not call this directly;
    it's here so an alternative broker impl can reuse the same shape."""
    return uuid.uuid4().hex
