"""Queue-backed grader transport — the throughput seam (ADR-0035, P3).

Where :class:`GraderRPCTrialGrader` gives the orchestrator *independent
deploy* (a grader on a different machine), the queue-backed transport gives
it *independent throughput scale*: the orchestrator publishes a grade job
and its worker thread returns immediately, freeing it to run the next
trial. A pool of grader workers consumes from the queue in parallel; the
scale knob is the consumer count. Native back-pressure is inherited from
the queue.

Two moving parts:

- :class:`GradeBroker` — Protocol for the transport. Producers call
  :meth:`publish_job` and get a :class:`concurrent.futures.Future` back;
  consumers call :meth:`next_job` (blocking) and :meth:`publish_result`.
- :class:`InMemoryGradeBroker` — a reference impl using
  :class:`queue.Queue` + a per-trial ``Future`` map. Ships as the
  in-process transport for tests, single-machine deployments, and the
  keyless integration-test tier. A Redis Streams (or RabbitMQ / SQS)
  backend plugs behind the same Protocol — deferred to a follow-up
  because the wire contract, the reference impl, and the plug-in seam
  can prove the throughput property today.

The plug-in seam consumer is
:class:`~tolokaforge.core.trial_grader.QueueTrialGrader`, registered
under the ``queue`` entry point.
"""

from __future__ import annotations

import queue
import threading
import uuid
from concurrent.futures import Future
from dataclasses import dataclass, field
from typing import Protocol, runtime_checkable

from tolokaforge.core.models import Grade

_CLOSE_SENTINEL: object = object()
"""Marker put on the queue by :meth:`InMemoryGradeBroker.close` so consumers
parked in :meth:`~InMemoryGradeBroker.next_job` (default ``timeout=None``)
unblock and terminate cleanly on shutdown."""


@dataclass(frozen=True)
class GradeJob:
    """A grade-request the producer puts on the queue.

    ``job_id`` is the join key between the producer (which blocks on a
    :class:`Future` keyed by it) and the consumer (which returns a
    :class:`GradeResult` carrying the same id). Producers should not
    read into ``job_id``'s value — it is opaque and generated by the
    broker.
    """

    job_id: str
    trial_id: str
    llm_messages_json: str
    termination_reason: str
    task_config_json: str
    agent_system_prompt: str


@dataclass(frozen=True)
class GradeResult:
    """A grade-response the consumer publishes back onto the broker."""

    job_id: str
    grade: Grade | None
    error: str = ""


@runtime_checkable
class GradeBroker(Protocol):
    """Transport surface the queue-backed grader dispatches through.

    Implementations may back onto any queue substrate (Redis Streams,
    RabbitMQ, SQS, an in-process :class:`queue.Queue`); the plug-in seam
    stays behind this Protocol.
    """

    def publish_job(self, job: GradeJob) -> Future[Grade | None]: ...

    def next_job(self, timeout: float | None = None) -> GradeJob | None: ...

    def publish_result(self, result: GradeResult) -> None: ...

    def close(self) -> None: ...


@dataclass
class _JobEntry:
    """Bookkeeping the in-memory broker keeps per-outstanding-job."""

    future: Future[Grade | None]


@dataclass
class InMemoryGradeBroker:
    """Reference :class:`GradeBroker` backed by a :class:`queue.Queue`.

    Thread-safe: producers on any thread can call :meth:`publish_job`,
    consumers on any thread can call :meth:`next_job` and
    :meth:`publish_result`. Ships as the in-process transport for tests
    and single-machine deployments; a Redis Streams (or other) backend
    plugs behind :class:`GradeBroker` without touching the seam
    consumer.

    The broker owns the per-job :class:`Future` — the producer receives
    it, the consumer's :meth:`publish_result` resolves it. Duplicate
    ``job_id`` on the wire is a broker-side bug (never generated
    externally in this impl), so :meth:`publish_result` on an unknown
    id is a loud ``KeyError`` rather than a silent drop.
    """

    _q: queue.Queue[GradeJob] = field(default_factory=queue.Queue)
    _futures: dict[str, _JobEntry] = field(default_factory=dict)
    _futures_lock: threading.Lock = field(default_factory=threading.Lock)
    _closed: bool = False

    def publish_job(self, job: GradeJob) -> Future[Grade | None]:
        if self._closed:
            raise RuntimeError("InMemoryGradeBroker is closed")
        future: Future[Grade | None] = Future()
        with self._futures_lock:
            self._futures[job.job_id] = _JobEntry(future=future)
        self._q.put(job)
        return future

    def next_job(self, timeout: float | None = None) -> GradeJob | None:
        try:
            job = self._q.get(timeout=timeout)
        except queue.Empty:
            return None
        # ``close()`` puts a sentinel on the queue so a consumer parked in
        # ``next_job(timeout=None)`` (the default) unblocks and terminates
        # cleanly instead of hanging on shutdown. Re-post the sentinel so
        # multiple consumers each see it.
        if job is _CLOSE_SENTINEL:
            self._q.put(_CLOSE_SENTINEL)
            return None
        return job

    def publish_result(self, result: GradeResult) -> None:
        with self._futures_lock:
            entry = self._futures.pop(result.job_id, None)
        if entry is None:
            raise KeyError(
                f"publish_result: no outstanding job {result.job_id!r} — "
                "duplicate id or job never published"
            )
        if result.error:
            entry.future.set_exception(RuntimeError(result.error))
        else:
            entry.future.set_result(result.grade)

    def close(self) -> None:
        self._closed = True
        # Unblock any consumer parked in ``next_job(timeout=None)``. The
        # sentinel re-posts itself so a pool of N consumers each terminates
        # rather than one racing ahead and starving the rest.
        self._q.put(_CLOSE_SENTINEL)
        with self._futures_lock:
            for entry in self._futures.values():
                if not entry.future.done():
                    entry.future.set_exception(RuntimeError("broker closed"))
            self._futures.clear()


def new_job_id() -> str:
    """Broker-side job-id generator. Callers should not call this directly;
    it's here so an alternative broker impl can reuse the same shape."""
    return uuid.uuid4().hex
