"""Pydantic models for configuration and data structures.

Per-concern submodules hold the actual definitions:

- :mod:`.grade_components` — :class:`GradeComponents`
- :mod:`.grade` — :class:`Grade` and the rubric-judge audit records
- :mod:`.trajectory` — :class:`Trajectory`, :class:`Message`,
  :class:`Metrics`, and the rate-limit probe accounting rows
- :mod:`.docker_config` — :class:`DockerConfig`, the ``docker:`` block
  ``RunConfig`` carries
- :mod:`.model_config` — :class:`ModelConfig` +
  :class:`OpenRouterConfig`
- :mod:`.docker_config` — :class:`DockerConfig`, the ``docker:`` block
  of ``run_config.yaml``
- :mod:`.run_config` — :class:`RunConfig` and every orchestrator /
  compute / storage / observability sub-block
- :mod:`.task_config` — :class:`TaskConfig`, :class:`ProjectConfig`,
  and the grading + defaults surface

This package's ``__init__`` is a re-export shim: every name a caller
imported via ``from tolokaforge.core.models import X`` before the split
is re-exported from here for a soft-migration window. New call sites
should prefer the submodule paths.

Types canonically defined outside this package (``runner.models`` wire
types, ``tools.registry`` enums) are re-exported here so a caller
reaches one module for the whole wire vocabulary.
"""

from tolokaforge.core.grading.combine_method import (
    CombineMethod,
    validate_combine_method,
)
from tolokaforge.core.grading.state_composition import resolve_hash_weight
from tolokaforge.core.llm.reasoning import ReasoningConfig, StructuredReasoning
from tolokaforge.core.llm.usage import CostSource, ProviderRawCall, Usage
from tolokaforge.core.models.grade import (
    CustomCheckDetail,
    Grade,
    JudgeInputs,
    JudgeKbGating,
    JudgeStatus,
    JudgeUsage,
)
from tolokaforge.core.models.grade_components import GradeComponents
from tolokaforge.core.models.model_config import ModelConfig, OpenRouterConfig
from tolokaforge.core.models.run_config import (
    DOCKER_RUNTIME_ALIAS_TARGET,
    LEGACY_DOCKER_RUNTIME_ALIAS,
    RATE_LIMIT_PROBE_ATTEMPT_CEILING_S,
    RATE_LIMIT_PROBE_MIN_EPISODE_S,
    USER_REPLY_MAX_ATTEMPTS,
    BundleStoreBackend,
    ComputeConfig,
    EngineConfig,
    EvaluationConfig,
    GraderConfig,
    GradingFindingSeverity,
    GradingValidationConfig,
    HarnessAdapterConfig,
    JudgeGraderConfig,
    LocalDiskBundleStoreConfig,
    LocalDockerComputeConfig,
    LocalStorageConfig,
    LoggingConfig,
    MetricsConfig,
    ObservabilityConfig,
    OrchestratorConfig,
    QueueGraderConfig,
    QueueStorageConfig,
    RateLimitProbeConfig,
    RunConfig,
    RunDefaults,
    S3BundleStoreConfig,
    S3StorageConfig,
    SnapshotBundleConfig,
    StorageBackend,
    StorageConfig,
    StuckHeuristics,
    TimeoutConfig,
    TracingConfig,
    TypeSenseConfig,
    require_user_simulator_config,
    validate_rate_limit_probe_budget,
)
from tolokaforge.core.models.task_config import (
    RETIRED_STATE_CHECK_KEYS,
    SEED_KIND_BY_EXTENSION,
    ActorSpec,
    AssetsConfig,
    GradingCombineConfig,
    GradingConfig,
    GradingDefaults,
    InitializationAction,
    InitialStateConfig,
    LLMJudgeDefaults,
    ProjectConfig,
    SeedKind,
    SeedRef,
    StateChecksConfig,
    StuckHeuristicsDefaults,
    TaskConfig,
    TaskDefaults,
    TaskDiscoveryConfig,
    TaskInventoryConfig,
    TaskMetadata,
    TimeoutDefaults,
    ToolsConfig,
    UserSimulatorConfig,
)
from tolokaforge.core.models.trajectory import (
    REPLY_DEFECT_EXCERPT_MAX_CHARS,
    FirstUserMessageSource,
    Message,
    MessageRole,
    Metrics,
    RateLimitProbeBucketMetrics,
    RateLimitProbeRoleMetrics,
    ReplyDefect,
    SnapshotOutcome,
    SnapshotStatus,
    ToolCall,
    ToolUsage,
    Trajectory,
    UserReplyGuardEvent,
    UserReplyOutcome,
)
from tolokaforge.core.models.trial_status import TerminationReason, TrialStatus

# Cross-package wire types re-exported so callers reach one module for
# the whole recorded-tool-call + wire-schema vocabulary. Canonical
# homes stay in ``runner.models`` (rubric / criterion / judge config /
# environment manifest / tool expectations / the transcript-rules block
# and its elements / service specs / recorded tool call / the trace-check
# matcher and constraint vocabulary) and ``tools.registry`` (tool
# execution status).
from tolokaforge.runner.models import (
    REQUESTOR_TO_EXECUTOR,
    AbsentBeforeConstraint,
    AbsentBetweenConstraint,
    AbsentConstraint,
    AdjacencyView,
    AnchorQuantifier,
    AnchorSide,
    BeforeConstraint,
    BoundValue,
    CommunicateInfo,
    CountConstraint,
    Criterion,
    CriterionResult,
    EnvironmentManifest,
    EnvironmentPatch,
    ImmediatelyBeforeConstraint,
    JudgeCustomization,
    KeyAccounting,
    KeyAccountingRecord,
    LLMJudgeConfig,
    MatcherSide,
    OnMissing,
    OnUnbound,
    PresentConstraint,
    Quantifier,
    ReadinessKind,
    ReadinessSpec,
    RecordedToolCall,
    RequiredAction,
    ResetSpec,
    Rubric,
    ServiceIsolation,
    ServiceNetworkAccess,
    ServiceSpec,
    StackPatch,
    ToolCallRecorder,
    ToolExecutorIdentity,
    ToolExpectations,
    TraceBinding,
    TraceChecksConfig,
    TraceChecksResult,
    TraceChecksSummary,
    TraceConstraint,
    TraceConstraintExpr,
    TraceConstraintKind,
    TraceConstraintResult,
    TraceConstraintSeverity,
    TraceMatcher,
    TracePath,
    TracePathResult,
    TranscriptRulesConfig,
    TurnWindow,
    ValuePredicate,
)
from tolokaforge.tools.registry import ToolExecutionStatus

__all__ = [
    # Grade concern
    "CustomCheckDetail",
    "Grade",
    "GradeComponents",
    "JudgeInputs",
    "JudgeKbGating",
    "JudgeStatus",
    "JudgeUsage",
    # Trajectory concern
    "REPLY_DEFECT_EXCERPT_MAX_CHARS",
    "FirstUserMessageSource",
    "Message",
    "MessageRole",
    "Metrics",
    "RateLimitProbeBucketMetrics",
    "RateLimitProbeRoleMetrics",
    "ReplyDefect",
    "SnapshotOutcome",
    "SnapshotStatus",
    "TerminationReason",
    "ToolCall",
    "ToolUsage",
    "Trajectory",
    "TrialStatus",
    "UserReplyGuardEvent",
    "UserReplyOutcome",
    # Model config
    "ModelConfig",
    "OpenRouterConfig",
    # Run config
    "BundleStoreBackend",
    "ComputeConfig",
    "DOCKER_RUNTIME_ALIAS_TARGET",
    "EngineConfig",
    "EvaluationConfig",
    "GraderConfig",
    "GradingFindingSeverity",
    "GradingValidationConfig",
    "HarnessAdapterConfig",
    "JudgeGraderConfig",
    "LEGACY_DOCKER_RUNTIME_ALIAS",
    "LocalDiskBundleStoreConfig",
    "LocalDockerComputeConfig",
    "LocalStorageConfig",
    "LoggingConfig",
    "MetricsConfig",
    "ObservabilityConfig",
    "OrchestratorConfig",
    "QueueGraderConfig",
    "QueueStorageConfig",
    "RATE_LIMIT_PROBE_ATTEMPT_CEILING_S",
    "RATE_LIMIT_PROBE_MIN_EPISODE_S",
    "RateLimitProbeConfig",
    "RunConfig",
    "RunDefaults",
    "S3BundleStoreConfig",
    "require_user_simulator_config",
    "S3StorageConfig",
    "SnapshotBundleConfig",
    "StorageBackend",
    "StorageConfig",
    "StuckHeuristics",
    "TimeoutConfig",
    "TracingConfig",
    "TypeSenseConfig",
    "USER_REPLY_MAX_ATTEMPTS",
    "validate_rate_limit_probe_budget",
    # Task config
    "ActorSpec",
    "AssetsConfig",
    "GradingCombineConfig",
    "GradingConfig",
    "GradingDefaults",
    "InitialStateConfig",
    "InitializationAction",
    "LLMJudgeDefaults",
    "ProjectConfig",
    "RETIRED_STATE_CHECK_KEYS",
    "SEED_KIND_BY_EXTENSION",
    "SeedKind",
    "SeedRef",
    "StateChecksConfig",
    "StuckHeuristicsDefaults",
    "TaskConfig",
    "TaskDefaults",
    "TaskDiscoveryConfig",
    "TaskInventoryConfig",
    "TaskMetadata",
    "TimeoutDefaults",
    "ToolsConfig",
    "UserSimulatorConfig",
    # Cross-package re-exports (runner.models canonical wire types)
    "REQUESTOR_TO_EXECUTOR",
    "AbsentBeforeConstraint",
    "AbsentBetweenConstraint",
    "AbsentConstraint",
    "AdjacencyView",
    "AnchorQuantifier",
    "AnchorSide",
    "BeforeConstraint",
    "BoundValue",
    "CommunicateInfo",
    "CountConstraint",
    "Criterion",
    "CriterionResult",
    "EnvironmentManifest",
    "EnvironmentPatch",
    "ImmediatelyBeforeConstraint",
    "JudgeCustomization",
    "KeyAccounting",
    "KeyAccountingRecord",
    "LLMJudgeConfig",
    "MatcherSide",
    "OnMissing",
    "OnUnbound",
    "PresentConstraint",
    "Quantifier",
    "ReadinessKind",
    "ReadinessSpec",
    "RecordedToolCall",
    "RequiredAction",
    "ResetSpec",
    "Rubric",
    "ServiceIsolation",
    "ServiceNetworkAccess",
    "ServiceSpec",
    "StackPatch",
    "ToolCallRecorder",
    "ToolExecutorIdentity",
    "ToolExpectations",
    "TraceBinding",
    "TraceChecksConfig",
    "TraceChecksResult",
    "TraceChecksSummary",
    "TraceConstraint",
    "TraceConstraintExpr",
    "TraceConstraintKind",
    "TraceConstraintResult",
    "TraceConstraintSeverity",
    "TraceMatcher",
    "TracePath",
    "TracePathResult",
    "TranscriptRulesConfig",
    "TurnWindow",
    "ValuePredicate",
    "ToolExecutionStatus",
    # Third-party sibling re-exports (kept for import-site compatibility)
    "CombineMethod",
    "CostSource",
    "ProviderRawCall",
    "ReasoningConfig",
    "StructuredReasoning",
    "Usage",
    "resolve_hash_weight",
    "validate_combine_method",
]
