# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from tolokaforge.executor import executor_pb2 as tolokaforge_dot_executor_dot_executor__pb2

GRPC_GENERATED_VERSION = "1.75.1"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in tolokaforge/executor/executor_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class ExecutorServiceStub:
    """Executor service - executes tools with access to environment"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecuteTool = channel.unary_unary(
            "/executor.ExecutorService/ExecuteTool",
            request_serializer=tolokaforge_dot_executor_dot_executor__pb2.ExecuteToolRequest.SerializeToString,
            response_deserializer=tolokaforge_dot_executor_dot_executor__pb2.ExecuteToolResponse.FromString,
            _registered_method=True,
        )
        self.RegisterTools = channel.unary_unary(
            "/executor.ExecutorService/RegisterTools",
            request_serializer=tolokaforge_dot_executor_dot_executor__pb2.RegisterToolsRequest.SerializeToString,
            response_deserializer=tolokaforge_dot_executor_dot_executor__pb2.RegisterToolsResponse.FromString,
            _registered_method=True,
        )
        self.HealthCheck = channel.unary_unary(
            "/executor.ExecutorService/HealthCheck",
            request_serializer=tolokaforge_dot_executor_dot_executor__pb2.HealthCheckRequest.SerializeToString,
            response_deserializer=tolokaforge_dot_executor_dot_executor__pb2.HealthCheckResponse.FromString,
            _registered_method=True,
        )


class ExecutorServiceServicer:
    """Executor service - executes tools with access to environment"""

    def ExecuteTool(self, request, context):
        """Execute a tool call"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def RegisterTools(self, request, context):
        """Register available tools for this trial"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def HealthCheck(self, request, context):
        """Health check"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_ExecutorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "ExecuteTool": grpc.unary_unary_rpc_method_handler(
            servicer.ExecuteTool,
            request_deserializer=tolokaforge_dot_executor_dot_executor__pb2.ExecuteToolRequest.FromString,
            response_serializer=tolokaforge_dot_executor_dot_executor__pb2.ExecuteToolResponse.SerializeToString,
        ),
        "RegisterTools": grpc.unary_unary_rpc_method_handler(
            servicer.RegisterTools,
            request_deserializer=tolokaforge_dot_executor_dot_executor__pb2.RegisterToolsRequest.FromString,
            response_serializer=tolokaforge_dot_executor_dot_executor__pb2.RegisterToolsResponse.SerializeToString,
        ),
        "HealthCheck": grpc.unary_unary_rpc_method_handler(
            servicer.HealthCheck,
            request_deserializer=tolokaforge_dot_executor_dot_executor__pb2.HealthCheckRequest.FromString,
            response_serializer=tolokaforge_dot_executor_dot_executor__pb2.HealthCheckResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "executor.ExecutorService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("executor.ExecutorService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class ExecutorService:
    """Executor service - executes tools with access to environment"""

    @staticmethod
    def ExecuteTool(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/executor.ExecutorService/ExecuteTool",
            tolokaforge_dot_executor_dot_executor__pb2.ExecuteToolRequest.SerializeToString,
            tolokaforge_dot_executor_dot_executor__pb2.ExecuteToolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def RegisterTools(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/executor.ExecutorService/RegisterTools",
            tolokaforge_dot_executor_dot_executor__pb2.RegisterToolsRequest.SerializeToString,
            tolokaforge_dot_executor_dot_executor__pb2.RegisterToolsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def HealthCheck(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/executor.ExecutorService/HealthCheck",
            tolokaforge_dot_executor_dot_executor__pb2.HealthCheckRequest.SerializeToString,
            tolokaforge_dot_executor_dot_executor__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
