# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from tolokaforge.runner import runner_pb2 as tolokaforge_dot_runner_dot_runner__pb2

GRPC_GENERATED_VERSION = "1.83.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in tolokaforge/runner/runner_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class RunnerServiceStub:
    """=============================================================================
    Runner Service - Main Host ↔ Runner communication
    =============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterTrial = channel.unary_unary(
            "/tolokaforge.runner.RunnerService/RegisterTrial",
            request_serializer=tolokaforge_dot_runner_dot_runner__pb2.RegisterTrialRequest.SerializeToString,
            response_deserializer=tolokaforge_dot_runner_dot_runner__pb2.RegisterTrialResponse.FromString,
            _registered_method=True,
        )
        self.ExecuteTool = channel.unary_unary(
            "/tolokaforge.runner.RunnerService/ExecuteTool",
            request_serializer=tolokaforge_dot_runner_dot_runner__pb2.ExecuteToolRequest.SerializeToString,
            response_deserializer=tolokaforge_dot_runner_dot_runner__pb2.ExecuteToolResponse.FromString,
            _registered_method=True,
        )
        self.GradeTrial = channel.unary_unary(
            "/tolokaforge.runner.RunnerService/GradeTrial",
            request_serializer=tolokaforge_dot_runner_dot_runner__pb2.GradeTrialRequest.SerializeToString,
            response_deserializer=tolokaforge_dot_runner_dot_runner__pb2.GradeTrialResponse.FromString,
            _registered_method=True,
        )
        self.GetState = channel.unary_unary(
            "/tolokaforge.runner.RunnerService/GetState",
            request_serializer=tolokaforge_dot_runner_dot_runner__pb2.GetStateRequest.SerializeToString,
            response_deserializer=tolokaforge_dot_runner_dot_runner__pb2.GetStateResponse.FromString,
            _registered_method=True,
        )
        self.ResetTrial = channel.unary_unary(
            "/tolokaforge.runner.RunnerService/ResetTrial",
            request_serializer=tolokaforge_dot_runner_dot_runner__pb2.ResetTrialRequest.SerializeToString,
            response_deserializer=tolokaforge_dot_runner_dot_runner__pb2.ResetTrialResponse.FromString,
            _registered_method=True,
        )
        self.CleanupTrial = channel.unary_unary(
            "/tolokaforge.runner.RunnerService/CleanupTrial",
            request_serializer=tolokaforge_dot_runner_dot_runner__pb2.CleanupTrialRequest.SerializeToString,
            response_deserializer=tolokaforge_dot_runner_dot_runner__pb2.CleanupTrialResponse.FromString,
            _registered_method=True,
        )
        self.HealthCheck = channel.unary_unary(
            "/tolokaforge.runner.RunnerService/HealthCheck",
            request_serializer=tolokaforge_dot_runner_dot_runner__pb2.HealthCheckRequest.SerializeToString,
            response_deserializer=tolokaforge_dot_runner_dot_runner__pb2.HealthCheckResponse.FromString,
            _registered_method=True,
        )


class RunnerServiceServicer:
    """=============================================================================
    Runner Service - Main Host ↔ Runner communication
    =============================================================================

    """

    def RegisterTrial(self, request, context):
        """Register a new trial with a typed TrialSpec payload.
        Host sends TrialSpec JSON; Runner reads spec.task to initialise the
        environment and uses spec.<other fields> for per-trial execution context.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ExecuteTool(self, request, context):
        """Execute a tool call from the LLM
        Host forwards tool call, Runner executes and returns output
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GradeTrial(self, request, context):
        """Grade the completed trial
        Host sends trajectory, Runner computes grade via golden path comparison
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetState(self, request, context):
        """Get current state snapshot - for debugging"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ResetTrial(self, request, context):
        """Reset trial state to initial - for retries"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CleanupTrial(self, request, context):
        """Forget a trial's registration entirely - for retry-after-transient-failure paths
        Idempotent: succeeds when the trial is not registered.
        Distinct from ResetTrial: ResetTrial keeps the registration and resets state;
        CleanupTrial removes the registration so the same trial_id can be re-registered.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def HealthCheck(self, request, context):
        """Health check"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_RunnerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "RegisterTrial": grpc.unary_unary_rpc_method_handler(
            servicer.RegisterTrial,
            request_deserializer=tolokaforge_dot_runner_dot_runner__pb2.RegisterTrialRequest.FromString,
            response_serializer=tolokaforge_dot_runner_dot_runner__pb2.RegisterTrialResponse.SerializeToString,
        ),
        "ExecuteTool": grpc.unary_unary_rpc_method_handler(
            servicer.ExecuteTool,
            request_deserializer=tolokaforge_dot_runner_dot_runner__pb2.ExecuteToolRequest.FromString,
            response_serializer=tolokaforge_dot_runner_dot_runner__pb2.ExecuteToolResponse.SerializeToString,
        ),
        "GradeTrial": grpc.unary_unary_rpc_method_handler(
            servicer.GradeTrial,
            request_deserializer=tolokaforge_dot_runner_dot_runner__pb2.GradeTrialRequest.FromString,
            response_serializer=tolokaforge_dot_runner_dot_runner__pb2.GradeTrialResponse.SerializeToString,
        ),
        "GetState": grpc.unary_unary_rpc_method_handler(
            servicer.GetState,
            request_deserializer=tolokaforge_dot_runner_dot_runner__pb2.GetStateRequest.FromString,
            response_serializer=tolokaforge_dot_runner_dot_runner__pb2.GetStateResponse.SerializeToString,
        ),
        "ResetTrial": grpc.unary_unary_rpc_method_handler(
            servicer.ResetTrial,
            request_deserializer=tolokaforge_dot_runner_dot_runner__pb2.ResetTrialRequest.FromString,
            response_serializer=tolokaforge_dot_runner_dot_runner__pb2.ResetTrialResponse.SerializeToString,
        ),
        "CleanupTrial": grpc.unary_unary_rpc_method_handler(
            servicer.CleanupTrial,
            request_deserializer=tolokaforge_dot_runner_dot_runner__pb2.CleanupTrialRequest.FromString,
            response_serializer=tolokaforge_dot_runner_dot_runner__pb2.CleanupTrialResponse.SerializeToString,
        ),
        "HealthCheck": grpc.unary_unary_rpc_method_handler(
            servicer.HealthCheck,
            request_deserializer=tolokaforge_dot_runner_dot_runner__pb2.HealthCheckRequest.FromString,
            response_serializer=tolokaforge_dot_runner_dot_runner__pb2.HealthCheckResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "tolokaforge.runner.RunnerService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("tolokaforge.runner.RunnerService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class RunnerService:
    """=============================================================================
    Runner Service - Main Host ↔ Runner communication
    =============================================================================

    """

    @staticmethod
    def RegisterTrial(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/tolokaforge.runner.RunnerService/RegisterTrial",
            tolokaforge_dot_runner_dot_runner__pb2.RegisterTrialRequest.SerializeToString,
            tolokaforge_dot_runner_dot_runner__pb2.RegisterTrialResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ExecuteTool(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/tolokaforge.runner.RunnerService/ExecuteTool",
            tolokaforge_dot_runner_dot_runner__pb2.ExecuteToolRequest.SerializeToString,
            tolokaforge_dot_runner_dot_runner__pb2.ExecuteToolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GradeTrial(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/tolokaforge.runner.RunnerService/GradeTrial",
            tolokaforge_dot_runner_dot_runner__pb2.GradeTrialRequest.SerializeToString,
            tolokaforge_dot_runner_dot_runner__pb2.GradeTrialResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetState(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/tolokaforge.runner.RunnerService/GetState",
            tolokaforge_dot_runner_dot_runner__pb2.GetStateRequest.SerializeToString,
            tolokaforge_dot_runner_dot_runner__pb2.GetStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ResetTrial(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/tolokaforge.runner.RunnerService/ResetTrial",
            tolokaforge_dot_runner_dot_runner__pb2.ResetTrialRequest.SerializeToString,
            tolokaforge_dot_runner_dot_runner__pb2.ResetTrialResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def CleanupTrial(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/tolokaforge.runner.RunnerService/CleanupTrial",
            tolokaforge_dot_runner_dot_runner__pb2.CleanupTrialRequest.SerializeToString,
            tolokaforge_dot_runner_dot_runner__pb2.CleanupTrialResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def HealthCheck(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/tolokaforge.runner.RunnerService/HealthCheck",
            tolokaforge_dot_runner_dot_runner__pb2.HealthCheckRequest.SerializeToString,
            tolokaforge_dot_runner_dot_runner__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )


class SubstrateServiceStub:
    """=============================================================================
    SubstrateService - read-only view of a trial's grading substrate.

    Exposed by the runner iff RunConfig.grader.expose_substrate is true. Serves
    the same trials the runner already holds; both servicers are registered on
    the same gRPC server + same listen port. Read-only by construction: the
    servicer implements no write handler and its class holds a _READ_ONLY
    invariant used by the read-only structural test. Distinct from
    RunnerService.GetState because a standalone grader needs the trial's WHOLE
    substrate (initial state, filesystem, KB) — not just the current DB dump.
    =============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReadInitialState = channel.unary_unary(
            "/tolokaforge.runner.SubstrateService/ReadInitialState",
            request_serializer=tolokaforge_dot_runner_dot_runner__pb2.ReadInitialStateRequest.SerializeToString,
            response_deserializer=tolokaforge_dot_runner_dot_runner__pb2.ReadStateResponse.FromString,
            _registered_method=True,
        )
        self.ReadFinalDBState = channel.unary_unary(
            "/tolokaforge.runner.SubstrateService/ReadFinalDBState",
            request_serializer=tolokaforge_dot_runner_dot_runner__pb2.ReadFinalDBStateRequest.SerializeToString,
            response_deserializer=tolokaforge_dot_runner_dot_runner__pb2.ReadStateResponse.FromString,
            _registered_method=True,
        )
        self.ReadFinalDBStateStable = channel.unary_unary(
            "/tolokaforge.runner.SubstrateService/ReadFinalDBStateStable",
            request_serializer=tolokaforge_dot_runner_dot_runner__pb2.ReadFinalDBStateStableRequest.SerializeToString,
            response_deserializer=tolokaforge_dot_runner_dot_runner__pb2.ReadStateResponse.FromString,
            _registered_method=True,
        )
        self.ReadFilesystemPath = channel.unary_unary(
            "/tolokaforge.runner.SubstrateService/ReadFilesystemPath",
            request_serializer=tolokaforge_dot_runner_dot_runner__pb2.ReadFilesystemPathRequest.SerializeToString,
            response_deserializer=tolokaforge_dot_runner_dot_runner__pb2.ReadFilesystemPathResponse.FromString,
            _registered_method=True,
        )
        self.ListFilesystemDir = channel.unary_unary(
            "/tolokaforge.runner.SubstrateService/ListFilesystemDir",
            request_serializer=tolokaforge_dot_runner_dot_runner__pb2.ListFilesystemDirRequest.SerializeToString,
            response_deserializer=tolokaforge_dot_runner_dot_runner__pb2.ListFilesystemDirResponse.FromString,
            _registered_method=True,
        )
        self.KBSearch = channel.unary_unary(
            "/tolokaforge.runner.SubstrateService/KBSearch",
            request_serializer=tolokaforge_dot_runner_dot_runner__pb2.KBSearchRequest.SerializeToString,
            response_deserializer=tolokaforge_dot_runner_dot_runner__pb2.KBSearchResponse.FromString,
            _registered_method=True,
        )
        self.RunDbProbe = channel.unary_unary(
            "/tolokaforge.runner.SubstrateService/RunDbProbe",
            request_serializer=tolokaforge_dot_runner_dot_runner__pb2.RunDbProbeRequest.SerializeToString,
            response_deserializer=tolokaforge_dot_runner_dot_runner__pb2.RunDbProbeResponse.FromString,
            _registered_method=True,
        )
        self.SubstrateHealthCheck = channel.unary_unary(
            "/tolokaforge.runner.SubstrateService/SubstrateHealthCheck",
            request_serializer=tolokaforge_dot_runner_dot_runner__pb2.SubstrateHealthCheckRequest.SerializeToString,
            response_deserializer=tolokaforge_dot_runner_dot_runner__pb2.SubstrateHealthCheckResponse.FromString,
            _registered_method=True,
        )


class SubstrateServiceServicer:
    """=============================================================================
    SubstrateService - read-only view of a trial's grading substrate.

    Exposed by the runner iff RunConfig.grader.expose_substrate is true. Serves
    the same trials the runner already holds; both servicers are registered on
    the same gRPC server + same listen port. Read-only by construction: the
    servicer implements no write handler and its class holds a _READ_ONLY
    invariant used by the read-only structural test. Distinct from
    RunnerService.GetState because a standalone grader needs the trial's WHOLE
    substrate (initial state, filesystem, KB) — not just the current DB dump.
    =============================================================================

    """

    def ReadInitialState(self, request, context):
        """Read the trial's pre-execution state ({table: [rows]})."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ReadFinalDBState(self, request, context):
        """Read the trial's post-execution DB state, RAW — mirrors
        db_client.get_state (unfiltered rows). Used by judge state-diff +
        custom_checks; parity depends on this NOT being papered over with the
        stable variant.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ReadFinalDBStateStable(self, request, context):
        """Read the trial's post-execution DB state, STABLE — mirrors
        db_client.get_stable_state (unstable fields filtered server-side by the
        DB service). Used by jsonpath state-checks grading.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ReadFilesystemPath(self, request, context):
        """Read one file under the trial's AGENT_WORK_DIR (path relative). Returns
        exists=false for a missing / non-file / symlink path; is_file=true with
        content_utf8 for text; is_file=true with content_bytes_b64 (base64) for
        any file that fails UTF-8 decode. Same filter and exclusion policy as
        tolokaforge.core.grading.filesystem_view.read_agent_visible_filesystem.
        Refuses reads under any AGENT_VISIBLE_EXCLUDES directory.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListFilesystemDir(self, request, context):
        """List rel-paths of every non-symlink UTF-8-decodable file under
        AGENT_WORK_DIR. Same filter and exclusion policy as
        tolokaforge.core.grading.filesystem_view.read_agent_visible_filesystem.
        Rel-paths returned in alphabetically-sorted order.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def KBSearch(self, request, context):
        """Query the trial's per-trial KB (rag-service). kb_available=false is a
        first-class signal ("this trial has no KB provisioned"); the callback
        substrate returns None from knowledge_search() when kb_available is
        false rather than dialing an unreachable endpoint.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def RunDbProbe(self, request, context):
        """Run a task-declared read-only SQL probe against the DSN in the runner
        container's network context. dsn + query are AUTHOR-DECLARED — the
        runner does not validate SQL shape; a probe query that mutates state
        is a pack authoring mistake. Returns rows encoded as a JSON array of
        objects; asyncpg-native scalars (datetime / Decimal / UUID / bytes)
        are coerced via json.dumps default=str, matching how
        ReadStateResponse.state_json handles the same types for DB state
        reads.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def SubstrateHealthCheck(self, request, context):
        """Substrate liveness + capacity signal. Distinct from RunnerService.
        HealthCheck (that endpoint reports RunnerService plumbing; this one
        reports the substrate seam and its active-trial count).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_SubstrateServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "ReadInitialState": grpc.unary_unary_rpc_method_handler(
            servicer.ReadInitialState,
            request_deserializer=tolokaforge_dot_runner_dot_runner__pb2.ReadInitialStateRequest.FromString,
            response_serializer=tolokaforge_dot_runner_dot_runner__pb2.ReadStateResponse.SerializeToString,
        ),
        "ReadFinalDBState": grpc.unary_unary_rpc_method_handler(
            servicer.ReadFinalDBState,
            request_deserializer=tolokaforge_dot_runner_dot_runner__pb2.ReadFinalDBStateRequest.FromString,
            response_serializer=tolokaforge_dot_runner_dot_runner__pb2.ReadStateResponse.SerializeToString,
        ),
        "ReadFinalDBStateStable": grpc.unary_unary_rpc_method_handler(
            servicer.ReadFinalDBStateStable,
            request_deserializer=tolokaforge_dot_runner_dot_runner__pb2.ReadFinalDBStateStableRequest.FromString,
            response_serializer=tolokaforge_dot_runner_dot_runner__pb2.ReadStateResponse.SerializeToString,
        ),
        "ReadFilesystemPath": grpc.unary_unary_rpc_method_handler(
            servicer.ReadFilesystemPath,
            request_deserializer=tolokaforge_dot_runner_dot_runner__pb2.ReadFilesystemPathRequest.FromString,
            response_serializer=tolokaforge_dot_runner_dot_runner__pb2.ReadFilesystemPathResponse.SerializeToString,
        ),
        "ListFilesystemDir": grpc.unary_unary_rpc_method_handler(
            servicer.ListFilesystemDir,
            request_deserializer=tolokaforge_dot_runner_dot_runner__pb2.ListFilesystemDirRequest.FromString,
            response_serializer=tolokaforge_dot_runner_dot_runner__pb2.ListFilesystemDirResponse.SerializeToString,
        ),
        "KBSearch": grpc.unary_unary_rpc_method_handler(
            servicer.KBSearch,
            request_deserializer=tolokaforge_dot_runner_dot_runner__pb2.KBSearchRequest.FromString,
            response_serializer=tolokaforge_dot_runner_dot_runner__pb2.KBSearchResponse.SerializeToString,
        ),
        "RunDbProbe": grpc.unary_unary_rpc_method_handler(
            servicer.RunDbProbe,
            request_deserializer=tolokaforge_dot_runner_dot_runner__pb2.RunDbProbeRequest.FromString,
            response_serializer=tolokaforge_dot_runner_dot_runner__pb2.RunDbProbeResponse.SerializeToString,
        ),
        "SubstrateHealthCheck": grpc.unary_unary_rpc_method_handler(
            servicer.SubstrateHealthCheck,
            request_deserializer=tolokaforge_dot_runner_dot_runner__pb2.SubstrateHealthCheckRequest.FromString,
            response_serializer=tolokaforge_dot_runner_dot_runner__pb2.SubstrateHealthCheckResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "tolokaforge.runner.SubstrateService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "tolokaforge.runner.SubstrateService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class SubstrateService:
    """=============================================================================
    SubstrateService - read-only view of a trial's grading substrate.

    Exposed by the runner iff RunConfig.grader.expose_substrate is true. Serves
    the same trials the runner already holds; both servicers are registered on
    the same gRPC server + same listen port. Read-only by construction: the
    servicer implements no write handler and its class holds a _READ_ONLY
    invariant used by the read-only structural test. Distinct from
    RunnerService.GetState because a standalone grader needs the trial's WHOLE
    substrate (initial state, filesystem, KB) — not just the current DB dump.
    =============================================================================

    """

    @staticmethod
    def ReadInitialState(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/tolokaforge.runner.SubstrateService/ReadInitialState",
            tolokaforge_dot_runner_dot_runner__pb2.ReadInitialStateRequest.SerializeToString,
            tolokaforge_dot_runner_dot_runner__pb2.ReadStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ReadFinalDBState(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/tolokaforge.runner.SubstrateService/ReadFinalDBState",
            tolokaforge_dot_runner_dot_runner__pb2.ReadFinalDBStateRequest.SerializeToString,
            tolokaforge_dot_runner_dot_runner__pb2.ReadStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ReadFinalDBStateStable(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/tolokaforge.runner.SubstrateService/ReadFinalDBStateStable",
            tolokaforge_dot_runner_dot_runner__pb2.ReadFinalDBStateStableRequest.SerializeToString,
            tolokaforge_dot_runner_dot_runner__pb2.ReadStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ReadFilesystemPath(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/tolokaforge.runner.SubstrateService/ReadFilesystemPath",
            tolokaforge_dot_runner_dot_runner__pb2.ReadFilesystemPathRequest.SerializeToString,
            tolokaforge_dot_runner_dot_runner__pb2.ReadFilesystemPathResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ListFilesystemDir(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/tolokaforge.runner.SubstrateService/ListFilesystemDir",
            tolokaforge_dot_runner_dot_runner__pb2.ListFilesystemDirRequest.SerializeToString,
            tolokaforge_dot_runner_dot_runner__pb2.ListFilesystemDirResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def KBSearch(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/tolokaforge.runner.SubstrateService/KBSearch",
            tolokaforge_dot_runner_dot_runner__pb2.KBSearchRequest.SerializeToString,
            tolokaforge_dot_runner_dot_runner__pb2.KBSearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def RunDbProbe(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/tolokaforge.runner.SubstrateService/RunDbProbe",
            tolokaforge_dot_runner_dot_runner__pb2.RunDbProbeRequest.SerializeToString,
            tolokaforge_dot_runner_dot_runner__pb2.RunDbProbeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def SubstrateHealthCheck(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/tolokaforge.runner.SubstrateService/SubstrateHealthCheck",
            tolokaforge_dot_runner_dot_runner__pb2.SubstrateHealthCheckRequest.SerializeToString,
            tolokaforge_dot_runner_dot_runner__pb2.SubstrateHealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
