# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""


import grpc

from tolokaforge.runner import runner_pb2 as runner__pb2

GRPC_GENERATED_VERSION = "1.76.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in runner_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class RunnerServiceStub:
    """=============================================================================
    Runner Service - Main Host ↔ Runner communication
    =============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterTrial = channel.unary_unary(
            "/tolokaforge.runner.RunnerService/RegisterTrial",
            request_serializer=runner__pb2.RegisterTrialRequest.SerializeToString,
            response_deserializer=runner__pb2.RegisterTrialResponse.FromString,
            _registered_method=True,
        )
        self.ExecuteTool = channel.unary_unary(
            "/tolokaforge.runner.RunnerService/ExecuteTool",
            request_serializer=runner__pb2.ExecuteToolRequest.SerializeToString,
            response_deserializer=runner__pb2.ExecuteToolResponse.FromString,
            _registered_method=True,
        )
        self.GradeTrial = channel.unary_unary(
            "/tolokaforge.runner.RunnerService/GradeTrial",
            request_serializer=runner__pb2.GradeTrialRequest.SerializeToString,
            response_deserializer=runner__pb2.GradeTrialResponse.FromString,
            _registered_method=True,
        )
        self.GetState = channel.unary_unary(
            "/tolokaforge.runner.RunnerService/GetState",
            request_serializer=runner__pb2.GetStateRequest.SerializeToString,
            response_deserializer=runner__pb2.GetStateResponse.FromString,
            _registered_method=True,
        )
        self.ResetTrial = channel.unary_unary(
            "/tolokaforge.runner.RunnerService/ResetTrial",
            request_serializer=runner__pb2.ResetTrialRequest.SerializeToString,
            response_deserializer=runner__pb2.ResetTrialResponse.FromString,
            _registered_method=True,
        )
        self.HealthCheck = channel.unary_unary(
            "/tolokaforge.runner.RunnerService/HealthCheck",
            request_serializer=runner__pb2.HealthCheckRequest.SerializeToString,
            response_deserializer=runner__pb2.HealthCheckResponse.FromString,
            _registered_method=True,
        )


class RunnerServiceServicer:
    """=============================================================================
    Runner Service - Main Host ↔ Runner communication
    =============================================================================

    """

    def RegisterTrial(self, request, context):
        """Register a new trial with full task description
        Host sends TaskDescription JSON, Runner initializes environment
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ExecuteTool(self, request, context):
        """Execute a tool call from the LLM
        Host forwards tool call, Runner executes and returns output
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GradeTrial(self, request, context):
        """Grade the completed trial
        Host sends trajectory, Runner computes grade via golden path comparison
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetState(self, request, context):
        """Get current state snapshot - for debugging"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ResetTrial(self, request, context):
        """Reset trial state to initial - for retries"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def HealthCheck(self, request, context):
        """Health check"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_RunnerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "RegisterTrial": grpc.unary_unary_rpc_method_handler(
            servicer.RegisterTrial,
            request_deserializer=runner__pb2.RegisterTrialRequest.FromString,
            response_serializer=runner__pb2.RegisterTrialResponse.SerializeToString,
        ),
        "ExecuteTool": grpc.unary_unary_rpc_method_handler(
            servicer.ExecuteTool,
            request_deserializer=runner__pb2.ExecuteToolRequest.FromString,
            response_serializer=runner__pb2.ExecuteToolResponse.SerializeToString,
        ),
        "GradeTrial": grpc.unary_unary_rpc_method_handler(
            servicer.GradeTrial,
            request_deserializer=runner__pb2.GradeTrialRequest.FromString,
            response_serializer=runner__pb2.GradeTrialResponse.SerializeToString,
        ),
        "GetState": grpc.unary_unary_rpc_method_handler(
            servicer.GetState,
            request_deserializer=runner__pb2.GetStateRequest.FromString,
            response_serializer=runner__pb2.GetStateResponse.SerializeToString,
        ),
        "ResetTrial": grpc.unary_unary_rpc_method_handler(
            servicer.ResetTrial,
            request_deserializer=runner__pb2.ResetTrialRequest.FromString,
            response_serializer=runner__pb2.ResetTrialResponse.SerializeToString,
        ),
        "HealthCheck": grpc.unary_unary_rpc_method_handler(
            servicer.HealthCheck,
            request_deserializer=runner__pb2.HealthCheckRequest.FromString,
            response_serializer=runner__pb2.HealthCheckResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "tolokaforge.runner.RunnerService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("tolokaforge.runner.RunnerService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class RunnerService:
    """=============================================================================
    Runner Service - Main Host ↔ Runner communication
    =============================================================================

    """

    @staticmethod
    def RegisterTrial(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/tolokaforge.runner.RunnerService/RegisterTrial",
            runner__pb2.RegisterTrialRequest.SerializeToString,
            runner__pb2.RegisterTrialResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ExecuteTool(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/tolokaforge.runner.RunnerService/ExecuteTool",
            runner__pb2.ExecuteToolRequest.SerializeToString,
            runner__pb2.ExecuteToolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GradeTrial(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/tolokaforge.runner.RunnerService/GradeTrial",
            runner__pb2.GradeTrialRequest.SerializeToString,
            runner__pb2.GradeTrialResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetState(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/tolokaforge.runner.RunnerService/GetState",
            runner__pb2.GetStateRequest.SerializeToString,
            runner__pb2.GetStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ResetTrial(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/tolokaforge.runner.RunnerService/ResetTrial",
            runner__pb2.ResetTrialRequest.SerializeToString,
            runner__pb2.ResetTrialResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def HealthCheck(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/tolokaforge.runner.RunnerService/HealthCheck",
            runner__pb2.HealthCheckRequest.SerializeToString,
            runner__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
